version: "3"
services:
  postgres:
    container_name: postgres-tribalyte
    image: postgres:14.4-alpine
    ports:
    - "5432:5432"
    env_file:
    - docker.env
    networks:
    - dbnet
    volumes:
    - tribalytedbdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin-tribalyte
    image: dpage/pgadmin4:6.11
    ports:
    - "6432:80"
    depends_on:
    - "postgres"
    env_file:
    - docker.env
    networks:
    - dbnet
    volumes:
    - pgadmindata-tribalyte:/var/lib/pgadmin
networks:
  dbnet:
    driver: bridge
volumes:
  tribalytedbdata:
    driver: local
  pgadmindata-tribalyte:
    driver: local
